import os
# os.rename('funkcii.py', '1.2.py')
# os.chdir('txt')
# os.chdir('..')
# os.chdir('..')
print(os.getcwd())
# os.makedirs('text_1/text_2/text_3')
# os.remove('1.py')
# os.removedirs('text_1/text_2/text_3')
os.rmdir('txt')